### PR TITLE
Added ServiceManager v3 support

### PR DESCRIPTION
**Pull request by zluiten**
Speaks for itself I guess :-)

### CODE REVIEW

**Review by prolic — APPROVED** [review]

**Comment by prolic** [comment]
Wow, people are still using it? I didn't check the download stats, but I didn't work on this lib for a long time.
Thanks for your PR.
MERGED

**Comment by zluiten** [comment]
Yep 😄 I'm updating an existing zend framework application. Thanks for the quick reponse! Could you tag a patch release as well?

**Comment by prolic** [comment]
Here you go https://github.com/prolic/HumusStreamResponseSender/releases/tag/v0.3.0

**Comment by zluiten** [comment]
🥇

**Pull request merged**
